### ISSUE TITLE
Create Recent Screen, style App, add animation

### ISSUE THREAD

**Issue by GeorgiyCox** [RushanCources/InteractionHistory#17]

**Comment by GeorgiyCox** [comment]
starte to create resent screen

**Comment by GeorgiyCox** [comment]
1. creating a slice of a request to the server
2. screen implementation

**Comment by GeorgiyCox** [comment]
adding styles for screens contacts, recent, details contact

**Comment by GeorgiyCox** [comment]
add animation

**Comment by GeorgiyCox** [comment]
Branch -  issue17_recentScreen,_styleApp_addAnimation

**Comment by rushanrr** [comment]
merged to main
