### ISSUE TITLE
Create "New Interaction" form

### ISSUE THREAD

**Issue by Lafien** [RushanCources/InteractionHistory#3]
Create "New Interaction" form according to  "/images/Create.png.png".
Note: Any changes and improvements are welcome.

**Comment by ZAHERSKIY** [comment]
Form created

**Comment by ZAHERSKIY** [comment]
Added validation on the email and description fields

**Comment by ZAHERSKIY** [comment]
Added form submitting

**Comment by ZAHERSKIY** [comment]
Implemented pre-filling fields according to data from the server

**Comment by rushanrr** [comment]
Branch issue3_new_interaction_form has been merged to main
